### ISSUE TITLE
Configuring conditional streaming

### ISSUE THREAD

**Issue by testrashmi** [ibm-cloud-docs/log-analysis#12]
https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-streaming-conditional

Hi, on this page:

https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-streaming-conditional

"5 -> Enter the exclusion criteria by adding a query. For more information on how to build a query, see Select the set of events to display through a view by applying a search query."

When you click on the link "Select the set of events to display through a view by applying a search query." -> https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-views#views_step2

It fails, that page does not exist.

Thank you.

**Comment by testrashmi** [comment]
![image](https://user-images.githubusercontent.com/52536794/148513540-45c1f471-3f18-4620-b26b-78c94d253638.png)

**Comment by testrashmi** [comment]
Please share the correct routing URL here

**Comment by vanadiscrawford** [comment]
Thank you for your comment.  The issue has been resolved and the corrected link published.
