### ISSUE TITLE
Getting information about logging agent images link leads to "Sorry, this content isn’t available".

### ISSUE THREAD

**Issue by yocreoquesi** [ibm-cloud-docs/log-analysis#2]
[Getting information about logging agent images](https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-logdna_agent_image) link in this doc is broken:
```
Sorry, this content isn’t available.
It seems we can’t find what you’re looking for.
```

**Comment by vanadiscrawford** [comment]
Thank you for bringing this to our attention.  We have corrected the link.  The correction will be available the next time this topic is published.
