### ISSUE TITLE
Could you add udp type of syslog private endpoints on the docs?

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/log-analysis#22]
Hello,
This is a doc issue about syslog private endpoint.

This page only describes tcp type of syslog private endpoints.( syslog-a.private.xx-xx.logging.cloud.ibm.com )
https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-endpoints#endpoints_syslog_private_endpoints

But it seems that there are udp type of syslog private endpoints and are working.(syslog-u.private.xx-xx.logging.cloud.ibm.com)
And some syslog agents only support udp protocol. 
So could you add udp type of syslog private endpoints on the docs?

$ ping syslog-u.private.jp-tok.logging.cloud.ibm.com
PING logdna-tokyo-usys.jp-tok.serviceendpoint.cloud.ibm.com (166.9.42.27) 56(84) bytes of data.
64 bytes from 1b.2a.09a6.ip4.static.sl-reverse.com (166.9.42.27): icmp_seq=1 ttl=63 time=0.683 ms
64 bytes from 1b.2a.09a6.ip4.static.sl-reverse.com (166.9.42.27): icmp_seq=2 ttl=63 time=0.466 ms
64 bytes from 1b.2a.09a6.ip4.static.sl-reverse.com (166.9.42.27): icmp_seq=3 ttl=63 time=0.499 ms

Thank you,

**Comment by lopezdsr** [comment]
In formation has been added

Thank you very much for your feedback.
