### ISSUE TITLE
resource_keys not necessary for ingestion key

### ISSUE THREAD

**Issue by knobutan** [ibm-cloud-docs/log-analysis#25]
https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-ingestion_key#ingestion_key_cli

In seection "Getting the ingestion key through the API" Step#4, it asks the user to create a new resource key to obtain the ingestion key. That is not the optimal way of getting the ingestion key. Instead, the doc should follow what it is doing in the section "Getting the ingestion key through the CLI"(https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-ingestion_key#ingestion_key_cli) and use the API equivalent of it.

**Comment by lopezdsr** [comment]
Instructions have been updated with the options a user has to obtain the ingestion.

Thank yiu very much for your feedback.
