### ISSUE TITLE
Check mark icon missing

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/log-analysis#3]
Two check mark icons are missing on this page
https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-config_api

![image](https://user-images.githubusercontent.com/12241613/119470926-16efab00-bd49-11eb-87b9-368622e4dc8b.png)

@lopezdsr

**Comment by vanadiscrawford** [comment]
Thank you for bringing this to our attention.  The issue has been resolved.  The missing check marks will be there the next time this topic is published.
