### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by mjspriggs** [ibm-cloud-docs/log-analysis#45]
To configure a logging agent you will need to:

    Understand your [storage requirements](https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-log_analysis_agent_storage).

    Install the appropriate agent for your environment: [Kubernetes](https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-log_analysis_agent_kube) or [Linux](https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-log_analysis_agent_linux).

    [Configure your agent.](https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-log_analysis_agent_config) 

I get "not found" for all these topics.

**Comment by vanadiscrawford** [comment]
Links fixed. Thanks for bringing this to our attention!
